# Permalinks
permalink:         /blog/:title

# Setup
title:               'Code or Die'
tagline:             'live to code'
description:         'Welcome to my kitchen'
url:                 http://nchristiny.com
baseurl:             ''

gems:
  # - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed

# Pagination
paginate:            6
paginate_path: "page:num"

excerpt_separator: <!--more-->

# Markdown
# Default
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

markdown_ext:  markdown,mkdown,mkdn,mkd,md

# RSS
feed:
  path: atom.xml

# About/contact
author:
  name:              Nick Christiny
  twitter:              https://twitter.com/chileannick
  email:             nchristiny@gmail.com

# Custom vars
version:             2.9.6
