# Permalinks
permalink:         /blog/:title

# Setup
title:               'Code or Die'
tagline:             'live to code'
description:         'Being the personal website/blog of software developer Nick Christiny.'
url:                 http://nchristiny.com
baseurl:             ''

# Gems
# gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-mentions, jemoji, jekyll-redirect-from]

gems:
  - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-assets

# Asset Pipeline
assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache: false
  cache_type: filesystem
  cdn: http://nchristiny.com/
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/"
  digest: true
  assets:
    - "app.css"
    - "app.js"
  sources:
    - _assets/css
    - _assets/js

# Pagination
paginate:            5
paginate_path: "page:num"

excerpt_separator: <!--more-->

# Markdown
# Default
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

markdown_ext:  markdown,mkdown,mkdn,mkd,md

# RSS
feed:
  path: atom.xml

# About/contact
author:
  name:              Nicholas Christiny
  twitter:              https://twitter.com/chileannick
  email:             nchristiny@gmail.com

# Custom vars
version:             2.8
