# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:         /blog/:title
# Deprecated in jekyll 3.0
# relative_permalinks: true

# Setup
title:               'Code or Die'
tagline:             'live to code'
description:         'Being the personal website, blog/note-to-self of software developer Nick Christiny.'
url:                 http://nchristiny.com
baseurl:             ''

# Gems
gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-mentions, jemoji, jekyll-redirect-from]

# Pagination
paginate:            5
paginate_path: "page:num"

excerpt_separator: <!--more-->

# Markdown
# Default
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

markdown_ext:  markdown,mkdown,mkdn,mkd,md

## Deprecated
# markdown: redcarpet
# redcarpet:
  # extensions: ["tables", "no_intra_emphasis", "autolink", "strikethrough", "superscript", "footnotes"]
# highlighter: pygments
## in favor of default rouge

# RSS
feed:
  path: atom.xml

# About/contact
author:
  name:              Nicholas Christiny
  twitter:              https://twitter.com/chileannick
  email:             nchristiny@gmail.com

# Custom vars
version:             2.2
