markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "autolink", "strikethrough", "superscript"]
highlighter: pygments
permalink: /blog/:year/:month/:day/:title
url: http://nchristiny.github.io

