# Permalinks
permalink:         /blog/:title

# Setup
title:               'Code or Die'
tagline:             'live to code'
description:         'Welcome to my kitchen'
url:                 http://nchristiny.com
baseurl:             ''

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# User settings
username: Nick Christiny
user_description: Freelance problem solver, hacker.
user_title: Yak Shaver Extraordinaire
email: nchristiny@gmail.com
twitter_username: ChileanNick
github_username:  nchristiny

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

markdown_ext:  markdown,mkdown,mkdn,mkd,md

# Pagination
# excerpt_separator: <!--more-->
paginate:            5
paginate_path: "page:num"

# Google-analytics
google-analytics:
  id: "UA-64368113-1"

exclude: ['package.json', 'src' , 'node_modules', 'gulpfile.js']

version:             3.1
