# Site settings
title: Event Horizon
email: nchristiny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! My name is Nick and I love developing code. In my spare time I enjoy thinking about extrasolar planetary climates and time travel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nchristiny.github.io" # the base hostname & protocol for your site
twitter_username: chileannick
github_username:  nchristiny

# Build settings
markdown: kramdown
