# Setup
title: Code or Die
tagline: Welcome to my kitchen
url: https://nchristiny.com
paginate: 3
description: >-
  Yak shaving tips, Infosec, 
  Astronomy, Gardening
baseurl: ""
permalink: /blog/:title.html

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Optimize Jekyll
exclude:
  - .sass-cache
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - cache/

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-64368113-1

# Specify the author for blog posts
author:
  name: Nick Christiny
  email: nick@nchristiny.com

# Custom vars
version: 4.2
